### PR TITLE
Updated with fixes and cleanup on dictionary attack and general codebase

### PR DESCRIPTION
**Pull request by donnajharris**
- Fixed the dictionary_crack() function to expect the hashed password as input.
- Added a folder (with README.md) with the dictionary_files.
- Tweaked hash.c and bruteforce.c so the -std=c99 standard could be removed from compilation line
- Updated main README.md with removal of -std=c99 (*except* for from the Docker instruction... I did not alter it.)
- Updated main README.md formatting

### CODE REVIEW

**Comment by donnajharris** [comment]
A separate question: What is the file "cypto"? It looks like another binary. Is it a library we need or an executable that got pulled in from the original commit?

**Comment by wandersonca** [comment]
@donnajharris, good catch, that binary was from some previous testing. I'll get this merged asap, and test it out later tonight.

**Comment by wandersonca** [comment]
There are vulgar words in that dictionary! we should eventually add a warning to README.md.

**Comment by donnajharris** [comment]
@wandersonca - Oh yes! I hadn't thought of that. I'm not a fan of such words, personally, but I should have thought to mention that. Do you think the disclaimer approach is the best or actually altering the data before the final submission?

**Comment by wandersonca** [comment]
@donnajharris a disclaimer in the README.md for that directory, as well as in the report would be good. For datasets larger than 100 it'd be difficult to try and remove all the bad words, another project in and of itself.

**Pull request merged**
